services:
  story_service:
    build: ./story_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./story_service/:/app/
    ports:
      - 8001:8000
    environment:
      - IAM_TOKEN=""

  llm_manager_service:
    build: ./llm_manager_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./llm_manager_service/:/app/
    ports:
      - 8002:8000
    environment:
      - IAM_TOKEN=""

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - story_service
      - llm_manager_service
