services:
  landing_service:
    build: ./landing_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./landing_service/:/app/
    ports:
      - 8000:8000
    depends_on:
      - story_service
      
  painter_service:
    build: ./painter_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./painter_service/:/app/
    ports:
      - 8004:8000

  story_service:
    build: ./story_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./story_service/:/app/
    ports:
      - 8001:8000
    depends_on:
      - llm_manager_service

  yc_access_service:
    build: ./yc_access_service
    command: python app/main.py
    volumes:
      - ./yc_access_service/:/app/
    environment:
      YC_KEYS_PATH: ${YC_KEYS_PATH}
    depends_on:
      - redis

  llm_manager_service:
    build: ./llm_manager_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./llm_manager_service/:/app/
    ports:
      - 8002:8000
    depends_on:
      - redis

  vlm_manager_service:
    build: ./vlm_manager_service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./vlm_manager_service/:/app/
    ports:
      - 8003:8000
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - story_service
      - yc_access_service
      - llm_manager_service

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: